name: Check code to errors
on:
  push:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run styles checking
        run: npm run style
      - name: run tests
        run: npm run test
      - name: Run build
        run: npm run build


